version: "3.8"
services:

  web:
    depends_on:
      - api
    build: ./client-boilerplate
    ports:
      - "3000:80"
    restart: always

  api:
    build: ./server-boilerplate
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DB_URL: your-mongodb-atlas-connection-string
    restart: always

  nginx:
    image: nginx:alpine
    depends_on:
      - web
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sites-available/sahajafashion.conf:/etc/nginx/conf.d/default.conf
    restart: always